version: "3"

services:
  app:
    build:
      context: ./docker/vue
    ports:
      - "3000:3000"
    volumes:
      - ./client:/projects
    tty: true
networks:
  multi_yml_network:
    external: true
